# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_mole',
        ),
    ]
