# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190820_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_mole',
            old_name='text',
            new_name='text_sheep',
        ),
    ]
